title = "OpenUniverse"
baseURL = "https://independent-eye2446.github.io/OpenUniverse-Website/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30 
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = [""]
  body_classes = "avenir  bg-lightest-blue"
  post_content_classes = "avenir  bg-white"
  favicon = "/icon.ico"
  site_logo = ""
  description = "A open-source space sandbox game."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/Independent-Eye2446/OpenUniverse"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "/rss"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/img/"
  recent_posts_number = 2

  [languages]
    [languages.en]
      contentDir = "content/english"
      languageName = "English"
      weight = 10
    [languages.de]
      contentDir = "content/german"
      languageName = "Deutsch"
      weight = 20
    
 [menu]

  [[menu.main]]
    identifier = "download"
    name = "Download"
    pre = "<i class='fa fa-heart'></i>"
    url = "/download/"
    weight = -120
  
  [[menu.main]]
    identifier = "html5"
    name = "Web Version"
    pre = "<i class='fa fa-heart'></i>"
    url = ""
    weight = -110

  [[menu.main]]
    name = "About"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/about/"
    weight = -100
